with-expecter: True
dir: internal/mocks/{{ replaceAll .InterfaceDirRelative "internal" "" }} 
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{ .InterfaceName | snakecase }}_mock.go"
all: True
packages:
  github.com/legrch/netgex:
    config:
      recursive: True