version: "3.8"

services:
  app:
    image: netgex:latest
    build: ../../..
    environment:
      # Service info
      - SERVICE_NAME=netgex
      - SERVICE_VERSION=1.0.0
      - ENVIRONMENT=development
      
      # Server config
      - GRPC_ADDRESS=:9090
      - HTTP_ADDRESS=:8080
      - METRICS_ADDRESS=:9091
      - PPROF_ADDRESS=:6060
      
      # Telemetry config - Legacy
      - TRACING_ENABLED=true
      - TRACING_BACKEND=jaeger
      - TRACING_ENDPOINT=http://jaeger:14268/api/traces
      - METRICS_ENABLED=true 
      - METRICS_BACKEND=prometheus
      - PROFILING_ENABLED=true
      - PROFILING_BACKEND=pprof
    ports:
      - "8080:8080"  # HTTP
      - "9090:9090"  # gRPC
      - "9091:9091"  # Metrics
      - "6060:6060"  # pprof
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
      - "14250:14250"
      - "9411:9411"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger 