// Code generated by mockery v2.53.3. DO NOT EDIT.

package server

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Process is an autogenerated mock type for the Process type
type Process struct {
	mock.Mock
}

type Process_Expecter struct {
	mock *mock.Mock
}

func (_m *Process) EXPECT() *Process_Expecter {
	return &Process_Expecter{mock: &_m.Mock}
}

// PreRun provides a mock function with given fields: ctx
func (_m *Process) PreRun(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PreRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Process_PreRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreRun'
type Process_PreRun_Call struct {
	*mock.Call
}

// PreRun is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Process_Expecter) PreRun(ctx interface{}) *Process_PreRun_Call {
	return &Process_PreRun_Call{Call: _e.mock.On("PreRun", ctx)}
}

func (_c *Process_PreRun_Call) Run(run func(ctx context.Context)) *Process_PreRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Process_PreRun_Call) Return(_a0 error) *Process_PreRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Process_PreRun_Call) RunAndReturn(run func(context.Context) error) *Process_PreRun_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *Process) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Process_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Process_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Process_Expecter) Run(ctx interface{}) *Process_Run_Call {
	return &Process_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *Process_Run_Call) Run(run func(ctx context.Context)) *Process_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Process_Run_Call) Return(_a0 error) *Process_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Process_Run_Call) RunAndReturn(run func(context.Context) error) *Process_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Process) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Process_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Process_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Process_Expecter) Shutdown(ctx interface{}) *Process_Shutdown_Call {
	return &Process_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *Process_Shutdown_Call) Run(run func(ctx context.Context)) *Process_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Process_Shutdown_Call) Return(_a0 error) *Process_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Process_Shutdown_Call) RunAndReturn(run func(context.Context) error) *Process_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcess creates a new instance of Process. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *Process {
	mock := &Process{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
