// Code generated by mockery v2.53.3. DO NOT EDIT.

package greeterv1

import (
	context "context"

	greeterv1 "github.com/legrch/netgex/examples/advanced/api/proto/v1"
	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// GreeterService_SayHelloStreamServer is an autogenerated mock type for the GreeterService_SayHelloStreamServer type
type GreeterService_SayHelloStreamServer struct {
	mock.Mock
}

type GreeterService_SayHelloStreamServer_Expecter struct {
	mock *mock.Mock
}

func (_m *GreeterService_SayHelloStreamServer) EXPECT() *GreeterService_SayHelloStreamServer_Expecter {
	return &GreeterService_SayHelloStreamServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *GreeterService_SayHelloStreamServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// GreeterService_SayHelloStreamServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type GreeterService_SayHelloStreamServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *GreeterService_SayHelloStreamServer_Expecter) Context() *GreeterService_SayHelloStreamServer_Context_Call {
	return &GreeterService_SayHelloStreamServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *GreeterService_SayHelloStreamServer_Context_Call) Run(run func()) *GreeterService_SayHelloStreamServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_Context_Call) Return(_a0 context.Context) *GreeterService_SayHelloStreamServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_Context_Call) RunAndReturn(run func() context.Context) *GreeterService_SayHelloStreamServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *GreeterService_SayHelloStreamServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GreeterService_SayHelloStreamServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type GreeterService_SayHelloStreamServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *GreeterService_SayHelloStreamServer_Expecter) RecvMsg(m interface{}) *GreeterService_SayHelloStreamServer_RecvMsg_Call {
	return &GreeterService_SayHelloStreamServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *GreeterService_SayHelloStreamServer_RecvMsg_Call) Run(run func(m interface{})) *GreeterService_SayHelloStreamServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_RecvMsg_Call) Return(_a0 error) *GreeterService_SayHelloStreamServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *GreeterService_SayHelloStreamServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *GreeterService_SayHelloStreamServer) Send(_a0 *greeterv1.SayHelloResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*greeterv1.SayHelloResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GreeterService_SayHelloStreamServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type GreeterService_SayHelloStreamServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *greeterv1.SayHelloResponse
func (_e *GreeterService_SayHelloStreamServer_Expecter) Send(_a0 interface{}) *GreeterService_SayHelloStreamServer_Send_Call {
	return &GreeterService_SayHelloStreamServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *GreeterService_SayHelloStreamServer_Send_Call) Run(run func(_a0 *greeterv1.SayHelloResponse)) *GreeterService_SayHelloStreamServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*greeterv1.SayHelloResponse))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_Send_Call) Return(_a0 error) *GreeterService_SayHelloStreamServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_Send_Call) RunAndReturn(run func(*greeterv1.SayHelloResponse) error) *GreeterService_SayHelloStreamServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *GreeterService_SayHelloStreamServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GreeterService_SayHelloStreamServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type GreeterService_SayHelloStreamServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *GreeterService_SayHelloStreamServer_Expecter) SendHeader(_a0 interface{}) *GreeterService_SayHelloStreamServer_SendHeader_Call {
	return &GreeterService_SayHelloStreamServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *GreeterService_SayHelloStreamServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *GreeterService_SayHelloStreamServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SendHeader_Call) Return(_a0 error) *GreeterService_SayHelloStreamServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *GreeterService_SayHelloStreamServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *GreeterService_SayHelloStreamServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GreeterService_SayHelloStreamServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type GreeterService_SayHelloStreamServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *GreeterService_SayHelloStreamServer_Expecter) SendMsg(m interface{}) *GreeterService_SayHelloStreamServer_SendMsg_Call {
	return &GreeterService_SayHelloStreamServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *GreeterService_SayHelloStreamServer_SendMsg_Call) Run(run func(m interface{})) *GreeterService_SayHelloStreamServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SendMsg_Call) Return(_a0 error) *GreeterService_SayHelloStreamServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *GreeterService_SayHelloStreamServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *GreeterService_SayHelloStreamServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GreeterService_SayHelloStreamServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type GreeterService_SayHelloStreamServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *GreeterService_SayHelloStreamServer_Expecter) SetHeader(_a0 interface{}) *GreeterService_SayHelloStreamServer_SetHeader_Call {
	return &GreeterService_SayHelloStreamServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *GreeterService_SayHelloStreamServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *GreeterService_SayHelloStreamServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SetHeader_Call) Return(_a0 error) *GreeterService_SayHelloStreamServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *GreeterService_SayHelloStreamServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *GreeterService_SayHelloStreamServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// GreeterService_SayHelloStreamServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type GreeterService_SayHelloStreamServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *GreeterService_SayHelloStreamServer_Expecter) SetTrailer(_a0 interface{}) *GreeterService_SayHelloStreamServer_SetTrailer_Call {
	return &GreeterService_SayHelloStreamServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *GreeterService_SayHelloStreamServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *GreeterService_SayHelloStreamServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SetTrailer_Call) Return() *GreeterService_SayHelloStreamServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *GreeterService_SayHelloStreamServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *GreeterService_SayHelloStreamServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}

// NewGreeterService_SayHelloStreamServer creates a new instance of GreeterService_SayHelloStreamServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGreeterService_SayHelloStreamServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GreeterService_SayHelloStreamServer {
	mock := &GreeterService_SayHelloStreamServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
