version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task -l

  run:
    desc: Run the example
    cmds:
      - go run main.go

  test:
    desc: Test the example
    cmds:
      - ./test.sh

  build:
    desc: Build the example
    cmds:
      - go build -o bin/v2-example main.go

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin 