// Code generated by mockery v2.53.3. DO NOT EDIT.

package splash

import (
	splash "github.com/legrch/netgex/splash"
	mock "github.com/stretchr/testify/mock"
)

// SplashOption is an autogenerated mock type for the SplashOption type
type SplashOption struct {
	mock.Mock
}

type SplashOption_Expecter struct {
	mock *mock.Mock
}

func (_m *SplashOption) EXPECT() *SplashOption_Expecter {
	return &SplashOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *SplashOption) Execute(_a0 *splash.Splash) {
	_m.Called(_a0)
}

// SplashOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SplashOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *splash.Splash
func (_e *SplashOption_Expecter) Execute(_a0 interface{}) *SplashOption_Execute_Call {
	return &SplashOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *SplashOption_Execute_Call) Run(run func(_a0 *splash.Splash)) *SplashOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*splash.Splash))
	})
	return _c
}

func (_c *SplashOption_Execute_Call) Return() *SplashOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *SplashOption_Execute_Call) RunAndReturn(run func(*splash.Splash)) *SplashOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewSplashOption creates a new instance of SplashOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSplashOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *SplashOption {
	mock := &SplashOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
